[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
vault = "3g2JPX4roASUJVacf68sBSpARk5m9B3hu9xeaE6mTjPR"

[programs.localnet]
vault = "3g2JPX4roASUJVacf68sBSpARk5m9B3hu9xeaE6mTjPR"

[provider]
cluster = "mainnet"
wallet = "~/.config/vexa/admin.json"

[scripts]
test = "cargo test -p vexa-vault"
